title: UNOSPACE
description: >- # this means to ignore newlines until "baseurl:"
  UNOSPACE Team Space.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://unospace.github.io" # the base hostname & protocol for your site, e.g. http://example.com

collections  : 
  posts      : 
    output   : true
    permalink: "/post/:year/:month/:title.html"
  pages      : 
    output   : true
    permalink: "/:name/index.html"

# Pagination
paginate     : 8
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

exclude:
   - Gemfile
   - Gemfile.lock
